feeds:
  - name: Financial Times World
    url: https://www.ft.com/world?format=rss

  - name: Financial Times Companies
    url: https://www.ft.com/companies?format=rss

  - name: The Hindu BusinessLine
    url: https://www.thehindubusinessline.com/feeder/default.rss

  - name: Financial Express
    url: https://www.financialexpress.com/feed/

  - name: Mint News
    url: https://www.livemint.com/rss/newsRSS

  - name: Mint Markets
    url: https://www.livemint.com/rss/marketsRSS

  - name: Mint Companies
    url: https://www.livemint.com/rss/companiesRSS

  - name: Times of India Home
    url: https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms

  - name: Times of India Business
    url: https://timesofindia.indiatimes.com/rssfeeds/1898055.cms

  - name: Hindustan Times India
    url: https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml

  - name: Hindustan Times World
    url: https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml

  - name: Indian Express Latest
    url: https://indianexpress.com/feed/

  - name: Indian Express India
    url: https://indianexpress.com/section/india/feed/

  - name: SCMP China
    url: https://www.scmp.com/rss/91/feed

  - name: SCMP Asia
    url: https://www.scmp.com/rss/92/feed

  - name: SCMP World
    url: https://www.scmp.com/rss/95/feed

  - name: ET B2B Top Stories
    url: https://b2b.economictimes.indiatimes.com/rss/topstories

  - name: ET B2B Energy
    url: https://b2b.economictimes.indiatimes.com/rss/energy

  - name: ET B2B Infra
    url: https://b2b.economictimes.indiatimes.com/rss/infra

  - name: ETCFO Top Stories
    url: https://cfo.economictimes.indiatimes.com/rss/topstories

  - name: ETCFO Policy
    url: https://cfo.economictimes.indiatimes.com/rss/policy